### ISSUE TITLE
How to convert YOLOv5 Model into a compatible file for tch

### ISSUE THREAD

**Issue by decodethedev** [igor-yusupov/rusty-yolo#2]
How would I convert my Yolov5 Model into a compatible file to use with it? because it's giving me errors like this: "[PytorchStreamReader failed locating file constants.pkl: file not found](https://discuss.pytorch.org/t/pytorchstreamreader-failed-locating-file-constants-pkl-file-not-found/169884)" Which I found out is because I'm using PyTorch exported model, so how would I convert it so I can use it?

**Comment by Nic-Gould** [comment]
Please see my fork [here](https://github.com/Nic-Gould/rusty-yolo/tree/main/models) and let me know if you're successful.

**Comment by igor-yusupov** [comment]
@decodethedev sorry for late answer. you can find the script here: https://github.com/igor-yusupov/rusty-yolo/tree/main/examples/simple_inference

**Comment by decodethedev** [comment]
Hi, I wanted to convert my custom Yolov5 Model to torchscript, how would I do that?
